option(ARGUS_PORTABLE "Constrain all native objects to the distribution CPU baseline" OFF)
option(ARGUS_TESTING "Build separate instrumented test library (never distribute)" OFF)
set(ARGUS_SANITIZER "" CACHE STRING "Native sanitizer: address or thread")
set(ARGUS_LLAMA_REVISION 60eeeb6082c1126bb8bc72902c83123cd056811b)
set(ARGUS_WHISPER_REVISION 306c88f4d1286aec1bf96e544632897886af5501)
set(ARGUS_CPU_BASELINE host)
if(ARGUS_PORTABLE)
    set(GGML_NATIVE OFF CACHE BOOL "Portable dependencies" FORCE)
    foreach(feature AVX_VNNI AVX512 AVX512_VBMI AVX512_VNNI AVX512_BF16 AMX_TILE AMX_INT8 AMX_BF16)
        set(GGML_${feature} OFF CACHE BOOL "Outside distribution baseline" FORCE)
    endforeach()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
        set(ARGUS_CPU_BASELINE x86-64-v3)
        foreach(feature SSE42 AVX AVX2 BMI2 FMA F16C)
            set(GGML_${feature} ON CACHE BOOL "Distribution baseline" FORCE)
        endforeach()
        if(MSVC)
            add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:/arch:AVX2>" "$<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=/arch:AVX2>")
        else()
            add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX,HIP>:-march=x86-64-v3>" "$<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=-march=x86-64-v3>")
        endif()
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
        set(ARGUS_CPU_BASELINE armv8-a)
        set(GGML_CPU_ARM_ARCH armv8-a CACHE STRING "Portable ARM baseline" FORCE)
        add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:-march=armv8-a>")
    else()
        message(FATAL_ERROR "Unsupported distribution architecture: ${CMAKE_SYSTEM_PROCESSOR}")
    endif()
endif()
if(ARGUS_SANITIZER)
    if(NOT ARGUS_SANITIZER MATCHES "^(address|thread)$" OR MSVC)
        message(FATAL_ERROR "Unsupported ARGUS_SANITIZER")
    endif()
    set(sanitizers ${ARGUS_SANITIZER})
    if(ARGUS_SANITIZER STREQUAL "address")
        set(sanitizers address,undefined)
    endif()
    add_compile_options(-fsanitize=${sanitizers} -fno-omit-frame-pointer)
    add_link_options(-fsanitize=${sanitizers})
endif()
find_package(Git QUIET)
set(ARGUS_SOURCE_REVISION unknown)
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse HEAD
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR} OUTPUT_VARIABLE ARGUS_SOURCE_REVISION
        OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE revision_status ERROR_QUIET)
    if(revision_status EQUAL 0)
        execute_process(COMMAND ${GIT_EXECUTABLE} -c core.fsmonitor=false diff --quiet HEAD
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR} RESULT_VARIABLE dirty ERROR_QUIET)
        if(dirty)
            string(APPEND ARGUS_SOURCE_REVISION -dirty)
        endif()
    else()
        set(ARGUS_SOURCE_REVISION unknown)
    endif()
endif()
file(READ "${CMAKE_SOURCE_DIR}/include/libargus.h" argus_header)
# Git may materialize this public text header with CRLF on Windows. The ABI
# identity describes declarations, not checkout line endings, so normalize
# conventional CRLF before hashing it for every platform artifact.
string(REPLACE "\r\n" "\n" argus_header "${argus_header}")
string(SHA256 ARGUS_ABI_HEADER_SHA256 "${argus_header}")
string(REGEX MATCHALL "ARGUS_API[^;]+;" argus_declarations "${argus_header}")
set(argus_exported_symbols "")
foreach(declaration IN LISTS argus_declarations)
    string(REGEX MATCH "argus_[a-zA-Z0-9_]+[ \n\r]*\\(" symbol "${declaration}")
    if(symbol)
        string(REGEX REPLACE "[ \n\r]*\\(" "" symbol "${symbol}")
        string(APPEND argus_exported_symbols "_${symbol}\n")
    endif()
endforeach()
file(WRITE "${CMAKE_BINARY_DIR}/argus.exports" "${argus_exported_symbols}")
configure_file("${CMAKE_SOURCE_DIR}/cmake/build_info.h.in"
    "${CMAKE_BINARY_DIR}/generated/argus_build_info.h" @ONLY)
function(argus_configure_target target)
    target_include_directories(${target} PRIVATE "${CMAKE_BINARY_DIR}/generated")
    set_target_properties(${target} PROPERTIES C_VISIBILITY_PRESET hidden
        CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra)
        if(NOT ARGUS_PORTABLE)
            target_compile_options(${target} PRIVATE -march=native)
        endif()
        if(UNIX AND NOT APPLE)
            target_link_options(${target} PRIVATE "LINKER:--exclude-libs,ALL")
        elseif(APPLE AND target STREQUAL "argus")
            target_link_options(${target} PRIVATE "LINKER:-exported_symbols_list,${CMAKE_BINARY_DIR}/argus.exports")
        endif()
    endif()
endfunction()
